@extends('layouts.app')

@section('title', 'Reports')
@section('subtitle', 'View report summaries generated by stored procedures')

@section('content')
<div class="space-y-8">
    <!-- Separator line -->
    <div class="border-b border-slate-200"></div>

    <!-- Filters and Export Section -->
    <div class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
        <div class="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
            <div class="flex flex-col gap-3 lg:flex-row">
                <div>
                    <label class="block text-sm font-semibold text-slate-900">From Date</label>
                    <input type="date" class="mt-2 rounded-lg border border-slate-300 px-4 py-2 text-sm focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-100">
                </div>
                <div>
                    <label class="block text-sm font-semibold text-slate-900">To Date</label>
                    <input type="date" class="mt-2 rounded-lg border border-slate-300 px-4 py-2 text-sm focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-100">
                </div>
            </div>
            <div class="flex gap-2">
                <button type="button" class="inline-flex items-center gap-2 rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-900 transition-all hover:bg-slate-50">
                    <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 4a1 1 0 011-1h16a1 1 0 011 1v2.586a1 1 0 01-.293.707l-6.414 6.414a1 1 0 00-.293.707V17l-4 4v-6.586a1 1 0 00-.293-.707L3.293 7.293A1 1 0 013 6.586V4z"></path></svg>
                    Filter
                </button>
                <button type="button" class="inline-flex items-center gap-2 rounded-lg border-2 border-blue-600 bg-gradient-to-r from-blue-600 to-blue-700 px-4 py-2 text-sm font-semibold text-white transition-all hover:from-blue-700 hover:to-blue-800" onclick="window.print()">
                    <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8"></path></svg>
                    PDF
                </button>
                <button type="button" class="inline-flex items-center gap-2 rounded-lg border-2 border-green-600 bg-gradient-to-r from-green-600 to-green-700 px-4 py-2 text-sm font-semibold text-white transition-all hover:from-green-700 hover:to-green-800">
                    <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path></svg>
                    CSV
                </button>
            </div>
        </div>
    </div>

    <!-- Current Stock Report -->
    <div class="rounded-xl border border-slate-200 bg-white shadow-sm">
        <div class="border-b border-slate-200 px-6 py-4">
            <h2 class="text-lg font-bold text-slate-900">Current Stock Report</h2>
            <p class="mt-1 text-sm text-slate-600">Real-time fuel inventory status across all tanks</p>
        </div>
        <div class="overflow-x-auto">
            <table class="w-full">
                <thead>
                    <tr class="border-b border-slate-200 bg-slate-50">
                        <th class="px-6 py-4 text-left text-xs font-bold uppercase tracking-wide text-slate-700">Fuel</th>
                        <th class="px-6 py-4 text-right text-xs font-bold uppercase tracking-wide text-slate-700">Stock</th>
                        <th class="px-6 py-4 text-right text-xs font-bold uppercase tracking-wide text-slate-700">Capacity</th>
                        <th class="px-6 py-4 text-right text-xs font-bold uppercase tracking-wide text-slate-700">Fill %</th>
                        <th class="px-6 py-4 text-right text-xs font-bold uppercase tracking-wide text-slate-700">Price/L</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-slate-100">
                    @forelse ($stockSummary as $stock)
                        <tr class="transition-colors hover:bg-slate-50">
                            <td class="px-6 py-4 text-sm font-medium text-slate-900">{{ $stock->fuel_name }}</td>
                            <td class="px-6 py-4 text-right text-sm text-slate-700">{{ number_format($stock->current_stock, 2) }} L</td>
                            <td class="px-6 py-4 text-right text-sm text-slate-700">{{ number_format($stock->capacity, 2) }} L</td>
                            <td class="px-6 py-4 text-right">
                                <span class="inline-flex items-center rounded-full bg-blue-100 px-2.5 py-0.5 text-xs font-semibold text-blue-700">{{ number_format($stock->percent_full, 1) }}%</span>
                            </td>
                            <td class="px-6 py-4 text-right text-sm font-semibold text-slate-900">₱{{ number_format($stock->price_per_liter, 2) }}</td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="5" class="px-6 py-12 text-center text-sm text-slate-500">No report data available.</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>

    <!-- Outstanding Credit Report -->
    <div class="rounded-xl border border-slate-200 bg-white shadow-sm">
        <div class="border-b border-slate-200 px-6 py-4">
            <h2 class="text-lg font-bold text-slate-900">Outstanding Credit Report</h2>
            <p class="mt-1 text-sm text-slate-600">Customers with pending credit balances</p>
        </div>
        <div class="overflow-x-auto">
            <table class="w-full">
                <thead>
                    <tr class="border-b border-slate-200 bg-slate-50">
                        <th class="px-6 py-4 text-left text-xs font-bold uppercase tracking-wide text-slate-700">Customer</th>
                        <th class="px-6 py-4 text-left text-xs font-bold uppercase tracking-wide text-slate-700">Contact</th>
                        <th class="px-6 py-4 text-right text-xs font-bold uppercase tracking-wide text-slate-700">Credit</th>
                        <th class="px-6 py-4 text-right text-xs font-bold uppercase tracking-wide text-slate-700">Balance</th>
                        <th class="px-6 py-4 text-center text-xs font-bold uppercase tracking-wide text-slate-700">Status</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-slate-100">
                    @forelse ($creditReport as $credit)
                        <tr class="transition-colors hover:bg-slate-50">
                            <td class="px-6 py-4 text-sm font-medium text-slate-900">{{ $credit->customer_name }}</td>
                            <td class="px-6 py-4 text-sm text-slate-700">{{ $credit->contact_number }}</td>
                            <td class="px-6 py-4 text-right text-sm font-medium text-slate-900">₱{{ number_format($credit->credit_amount, 2) }}</td>
                            <td class="px-6 py-4 text-right text-sm font-bold text-red-600">₱{{ number_format($credit->balance, 2) }}</td>
                            <td class="px-6 py-4 text-center">
                                @if(strtolower($credit->status) === 'pending')
                                    <span class="inline-flex items-center rounded-full bg-amber-100 px-2.5 py-0.5 text-xs font-semibold text-amber-700">Pending</span>
                                @elseif(strtolower($credit->status) === 'active')
                                    <span class="inline-flex items-center rounded-full bg-red-100 px-2.5 py-0.5 text-xs font-semibold text-red-700">Active</span>
                                @else
                                    <span class="inline-flex items-center rounded-full bg-green-100 px-2.5 py-0.5 text-xs font-semibold text-green-700">Resolved</span>
                                @endif
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="5" class="px-6 py-12 text-center text-sm text-slate-500">No credit report data available.</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>

    <!-- Shift Summary Report -->
    <div class="rounded-xl border border-slate-200 bg-white shadow-sm">
        <div class="border-b border-slate-200 px-6 py-4">
            <h2 class="text-lg font-bold text-slate-900">Daily Shift Summary</h2>
            <p class="mt-1 text-sm text-slate-600">Sales and transaction summary by shift</p>
        </div>
        <div class="overflow-x-auto">
            <table class="w-full">
                <thead>
                    <tr class="border-b border-slate-200 bg-slate-50">
                        <th class="px-6 py-4 text-left text-xs font-bold uppercase tracking-wide text-slate-700">Date</th>
                        <th class="px-6 py-4 text-right text-xs font-bold uppercase tracking-wide text-slate-700">Liters</th>
                        <th class="px-6 py-4 text-right text-xs font-bold uppercase tracking-wide text-slate-700">Gross Sales</th>
                        <th class="px-6 py-4 text-right text-xs font-bold uppercase tracking-wide text-slate-700">Net Sales</th>
                        <th class="px-6 py-4 text-right text-xs font-bold uppercase tracking-wide text-slate-700">Credit</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-slate-100">
                    @forelse ($shiftSummary as $shift)
                        <tr class="transition-colors hover:bg-slate-50">
                            <td class="px-6 py-4 text-sm font-medium text-slate-900">{{ $shift->sales_date }}</td>
                            <td class="px-6 py-4 text-right text-sm text-slate-700">{{ number_format($shift->total_liters, 2) }} L</td>
                            <td class="px-6 py-4 text-right text-sm font-semibold text-slate-900">₱{{ number_format($shift->gross_sales, 2) }}</td>
                            <td class="px-6 py-4 text-right text-sm font-semibold text-green-600">₱{{ number_format($shift->net_sales, 2) }}</td>
                            <td class="px-6 py-4 text-right text-sm text-slate-700">₱{{ number_format($shift->total_credit, 2) }}</td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="5" class="px-6 py-12 text-center text-sm text-slate-500">No shift summary available.</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection
