@extends('layouts.app')

@section('title', 'Reports')
@section('subtitle', 'View report summaries generated by stored procedures')

@section('content')
<div class="grid gap-6 lg:grid-cols-3">
    <div class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm lg:col-span-3">
        <h2 class="text-lg font-semibold text-slate-900">Current Stock Report</h2>
        <div class="mt-6 overflow-x-auto">
            <table class="min-w-full text-left text-sm text-slate-600">
                <thead class="border-b border-slate-200 text-slate-500">
                    <tr>
                        <th class="px-3 py-3">Fuel</th>
                        <th class="px-3 py-3">Stock</th>
                        <th class="px-3 py-3">Capacity</th>
                        <th class="px-3 py-3">Percent</th>
                        <th class="px-3 py-3">Price / L</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-slate-200">
                    @forelse ($stockSummary as $stock)
                        <tr>
                            <td class="px-3 py-4">{{ $stock->fuel_name }}</td>
                            <td class="px-3 py-4">{{ number_format($stock->current_stock, 3) }} L</td>
                            <td class="px-3 py-4">{{ number_format($stock->capacity, 3) }} L</td>
                            <td class="px-3 py-4">{{ number_format($stock->percent_full, 1) }}%</td>
                            <td class="px-3 py-4">₱{{ number_format($stock->price_per_liter, 2) }}</td>
                        </tr>
                    @empty
                        <tr><td colspan="5" class="px-3 py-4 text-slate-500">No report data available.</td></tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>

    <div class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm lg:col-span-3">
        <h2 class="text-lg font-semibold text-slate-900">Outstanding Credit Report</h2>
        <div class="mt-6 overflow-x-auto">
            <table class="min-w-full text-left text-sm text-slate-600">
                <thead class="border-b border-slate-200 text-slate-500">
                    <tr>
                        <th class="px-3 py-3">Customer</th>
                        <th class="px-3 py-3">Contact</th>
                        <th class="px-3 py-3">Credit</th>
                        <th class="px-3 py-3">Balance</th>
                        <th class="px-3 py-3">Status</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-slate-200">
                    @forelse ($creditReport as $credit)
                        <tr>
                            <td class="px-3 py-4">{{ $credit->customer_name }}</td>
                            <td class="px-3 py-4">{{ $credit->contact_number }}</td>
                            <td class="px-3 py-4">₱{{ number_format($credit->credit_amount, 2) }}</td>
                            <td class="px-3 py-4">₱{{ number_format($credit->balance, 2) }}</td>
                            <td class="px-3 py-4">{{ ucfirst($credit->status) }}</td>
                        </tr>
                    @empty
                        <tr><td colspan="5" class="px-3 py-4 text-slate-500">No credit report data available.</td></tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>

    <div class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm lg:col-span-3">
        <h2 class="text-lg font-semibold text-slate-900">Today Shift Summary</h2>
        <div class="mt-6 overflow-x-auto">
            <table class="min-w-full text-left text-sm text-slate-600">
                <thead class="border-b border-slate-200 text-slate-500">
                    <tr>
                        <th class="px-3 py-3">Date</th>
                        <th class="px-3 py-3">Liters</th>
                        <th class="px-3 py-3">Gross</th>
                        <th class="px-3 py-3">Net</th>
                        <th class="px-3 py-3">Credit</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-slate-200">
                    @forelse ($shiftSummary as $shift)
                        <tr>
                            <td class="px-3 py-4">{{ $shift->sales_date }}</td>
                            <td class="px-3 py-4">{{ number_format($shift->total_liters, 3) }} L</td>
                            <td class="px-3 py-4">₱{{ number_format($shift->gross_sales, 2) }}</td>
                            <td class="px-3 py-4">₱{{ number_format($shift->net_sales, 2) }}</td>
                            <td class="px-3 py-4">₱{{ number_format($shift->total_credit, 2) }}</td>
                        </tr>
                    @empty
                        <tr><td colspan="5" class="px-3 py-4 text-slate-500">No shift summary available.</td></tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection
